cities:
  - Айтос
  - Аксаково
  - Алфатар
  - Антоново
  - Априлци
  - Ардино
  - Асеновград
  - Ахелой
  - Ахтопол
  - Балчик
  - Банкя
  - Банско
  - Баня
  - Батак
  - Батановци
  - Белене
  - Белица
  - Белово
  - Белоградчик
  - Белослав
  - Берковица
  - Благоевград
  - Бобов дол
  - Бобошево
  - Божурище
  - Бойчиновци
  - Болярово
  - Борово
  - Ботевград
  - Брацигово
  - Брегово
  - Брезник
  - Брезово
  - Брусарци
  - Бургас
  - Бухово
  - Българово
  - Бяла (Област Варна)
  - Бяла (Област Русе)
  - Бяла Слатина
  - Бяла Черква
  - Варна
  - Велики Преслав
  - Велико Търново
  - Велинград
  - Ветово
  - Ветрен
  - Видин
  - Враца
  - Вълчедръм
  - Вълчи дол
  - Върбица
  - Вършец
  - Габрово
  - Генерал Тошево
  - Главиница
  - Глоджево
  - Годеч
  - Горна Оряховица
  - Гоце Делчев
  - Грамада
  - Гулянци
  - Гурково
  - Гълъбово
  - Две могили
  - Дебелец
  - Девин
  - Девня
  - Джебел
  - Димитровград
  - Димово
  - Добрич
  - Долна Митрополия
  - Долна Оряховица
  - Долна баня
  - Долни Дъбник
  - Долни чифлик
  - Доспат
  - Драгоман
  - Дряново
  - Дулово
  - Дунавци
  - Дупница
  - Дългопол
  - Елена
  - Елин Пелин
  - Елхово
  - Етрополе
  - Завет
  - Земен
  - Златарица
  - Златица
  - Златоград
  - Ивайловград
  - Искър
  - Исперих
  - Ихтиман
  - Каблешково
  - Каварна
  - Казанлък
  - Калофер
  - Камено
  - Каолиново
  - Карлово
  - Карнобат
  - Каспичан
  - Кермен
  - Килифарево
  - Китен
  - Китен (Област Варна)
  - Клисура
  - Кнежа
  - Козлодуй
  - Койнаре
  - Копривщица
  - Костандово
  - Костенец
  - Костинброд
  - Котел
  - Кочериново
  - Кресна
  - Криводол
  - Кричим
  - Крумовград
  - Кубрат
  - Куклен
  - Кула
  - Кърджали
  - Кюстендил
  - Левски
  - Летница
  - Ловеч
  - Лозница
  - Лом
  - Луковит
  - Лъки
  - Любимец
  - Лясковец
  - Мадан
  - Маджарово
  - Малко Търново
  - Мартен
  - Мездра
  - Мелник
  - Меричлери
  - Мизия
  - Момчилград
  - Монтана
  - Мъглиж
  - Неделино
  - Несебър
  - Николаево
  - Никопол
  - Нова Загора
  - Нови Искър
  - Нови пазар
  - Обзор
  - Омуртаг
  - Опака
  - Оряхово
  - Павел баня
  - Павликени
  - Пазарджик
  - Панагюрище
  - Перник
  - Перущица
  - Петрич
  - Пещера
  - Пирдоп
  - Плачковци
  - Плевен
  - Плиска
  - Пловдив
  - Полски Тръмбеш
  - Поморие
  - Попово
  - Пордим
  - Правец
  - Приморско
  - Провадия
  - Първомай
  - Раднево
  - Радомир
  - Разград
  - Разлог
  - Ракитово
  - Раковски
  - Рила
  - Роман
  - Рудозем
  - Русе
  - Садово
  - Самоков
  - Сандански
  - Сапарева баня
  - Свиленград
  - Свищов
  - Своге
  - Севлиево
  - Сеново
  - Септември
  - Силистра
  - Симеоновград
  - Симитли
  - Славяново
  - Сливен
  - Сливница
  - Сливо поле
  - Смолян
  - Смядово
  - Созопол
  - Сопот
  - София
  - Средец
  - Стамболийски
  - Стара Загора
  - Стражица
  - Стралджа
  - Стрелча
  - Суворово
  - Сунгурларе
  - Сухиндол
  - Съединение
  - Сърница
  - Твърдица
  - Тервел
  - Тетевен
  - Тополовград
  - Троян
  - Трън
  - Тръстеник
  - Трявна
  - Тутракан
  - Търговище
  - Угърчин
  - Хаджидимово
  - Харманли
  - Хасково
  - Хисаря
  - Цар Калоян
  - Царево
  - Чепеларе
  - Червен бряг
  - Чипровци
  - Чирпан
  - Шабла
  - Шивачево
  - Шипка
  - Шумен
  - Ябланица
  - Якоруда
  - Ямбол
  